Update validate.yml

diff --git a/.github/workflows/validate.yml b/.github/workflows/validate.yml
--- a/.github/workflows/validate.yml
+++ b/.github/workflows/validate.yml
@@ -11,6 +11,9 @@ on:
     paths:
       - "force-app/main/default/**"
 
+  # Trigger the workflow manually
+  workflow_dispatch:
+
 permissions:
   contents: write
 
@@ -143,23 +146,12 @@ jobs:
 
       - name: Commit Validation Summary
         if: always()
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
+          # Check if ValidationSummary.txt exists, commit changes
           if [ -f "deployment/ValidationSummary.txt" ]; then
             git config --local user.email "github-actions[bot]@users.noreply.github.com"
             git config --local user.name "github-actions[bot]"
-
-            # if the branch is correctly checked out
-            git fetch origin
-            git checkout "${{ github.ref_name }}"
-
-            # Stage and commit the validation summary
             git add deployment/ValidationSummary.txt
             git commit -m "Add deployment validation results [skip ci]" || echo "No changes to commit"
-
-            # Push changes back to the repository
-            REPO_URL="https://${GITHUB_TOKEN}@github.com/${{ github.repository }}"
-            git push "$REPO_URL" HEAD:${{ github.ref_name }}
-          else
-            echo "ValidationSummary.txt not found. Skipping commit."
+            git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }} || echo "Failed to push changes"
+          fi
